### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property 'notify' of undefined.

### ISSUE THREAD

**Issue by chalme** [inherd/uncode#4]
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/17763926/117541174-33030500-b045-11eb-939f-067b1e32b467.png">
<img width="843" alt="image" src="https://user-images.githubusercontent.com/17763926/117541771-03a1c780-b048-11eb-9dfb-5814ba7fd26f.png">

网址打开，浏览器控制台就报错了。  过几秒钟自动弹出错误页面。 关闭错误页面，过几秒也会弹出错误

**Comment by what0o0** [comment]
## 环境
```
OS：macOS 10.15.7
NodeJS：v12.13.0
```
## 操作
鼠标双击 `Save Config`过几秒钟出现下面错误提示

### Unhandled Rejection (TypeError): window.rpc is undefined
emit_event
src/uncode-bridge.ts:106

```
  103 | },
  104 | 
  105 | emit_event: function (event_type: string, payload: object) {
> 106 |   emit(
  107 |     'js_event',
  108 |     JSON.stringify({
  109 |       event_type: event_type,`
```
save_config
src/uncode-bridge.ts:86
```
  83 | 
  84 | save_config(config: any) {
  85 |   this.set_config(config);
> 86 |   this.emit_event('save_config', this.config);
  87 | },
  88 | 
  89 | open_dialog(): Promise<any> {
```
saveConfig
src/app/pages/HomePage/index.tsx:29
```
  26 | };
  27 | 
  28 | const saveConfig = () => {
> 29 |   UncodeBridge.save_config(config);
  30 | };
  31 | 
  32 | const editorDidMount = (
```

**Comment by phodal** [comment]
不能在浏览器里打开~~，我看一下怎么兼容吧
